[package]
name = "ferrisfollow"
version = "0.1.1"
edition = "2024"

[dependencies]
petgraph = "0.8.1"
syn = { version = "2.0", features = ["full", "visit", "extra-traits"] }
toml = "0.8.20"
walkdir = "2.3"
